### ISSUE TITLE
Progression bar

### ISSUE THREAD

**Issue by ghost** [rspeer/wiki2text#3]
Hello,

First thank you for this project.
1. Is there a way to show a progression bar or percentage ?
2. Does the -t argument makes the output size bigger or of same size as without -t ?

**Comment by rspeer** [comment]
I believe that there's no efficient way to show a progress bar. Notice that what wiki2text takes as input is a stream coming out of `bunzip2`. It can't know where it is in that stream unless it waits to read the entire stream, which would roughly double its running time.

When I run it, I keep track of progress by looking at the file size and having a vague idea of how many gigabytes it should be when it's done.

The `-t` argument should give you output that's slightly bigger: spaces are getting replaced by line breaks, but line breaks also get inserted next to punctuation.
